version: '3.8'

services:
  pompui-landing:
    build: ./sites/landing-page
    container_name: pompui-landing
    networks:
      - pompui-network
      - web-network
    restart: always

  pompui-garden-journal:
    build: ./sites/garden-journal
    container_name: pompui-garden-journal
    networks:
      - pompui-network
      - web-network
    restart: always

networks:
  pompui-network:
    driver: bridge
  web-network:
    # Shared network created by the DHde project's global-proxy.
    name: daniel-hettichde_web-network
    external: true